server: 
  port: 8082
  # 配置JSP变动后自动编译加载
  servlet.jsp.init-parameters.development: true

spring:
  # 数据库配置
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/maintenance?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    #druid是spring默认的数据库连接池
    #type: com.alibaba.druid.pool.DruidDataSource
    #数据库驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
  # 配置JSP
  mvc.view: 
    prefix: /WEB-INF/jsp/
    suffix: .jsp
  # 代码修改自动重启
  devtools.restart: 
    enabled: true #热加载生效
    additional-paths: src/main/java #额外新增的热加载目录
    #exclude:  #热加载排除目录

# 驼峰式命名数据库类
mybatis:
  #将_转化成驼峰命名
  typeAliasesPackage: com.maicai.entity
  mapperLocations: classpath:mybatis/mapper/*.xml
  configuration:
    #将_转化成驼峰命名
    map-underscore-to-camel-case: true
      
