server:
  port: 8083

# 数据库配置
spring:
  datasource:
    username: root
    password: root1111
    #url: jdbc:mysql://localhost:3306/maicai?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

# 驼峰式命名数据库类
mybatis:
  typeAliasesPackage: com.maicai.entity
  mapperLocations: classpath:mybatis/mapper/*.xml
  configuration:
      map-underscore-to-camel-case: true